### ISSUE TITLE
[Question] How it is different  from using the firestore.js goolge web library

### ISSUE THREAD

**Issue by pavankumarkatakam** [ReallySmallSoftware/cordova-plugin-firestore#10]
Are there any features that are not available via web library and included in this package?
Is this package support offline data syncing to firestore when mobile has internet connected but APP is in terminated state?

**Comment by ReallySmallSoftware** [comment]
Hello. There are no extra features, indeed there will be some missing at the moment.

However, the intention was that by being written in native code the features that were supported might be faster, more secure (using phone storage rather than webview for example) and better able to support offline operation.

The syncing doesn't happen if the app is terminated, but as good as, as when the app is restarted the sync process happens transparently. Full offline mode is supported, with local/remote writes being synched when the device comes back online.

**Comment by pavankumarkatakam** [comment]
> The syncing doesn't happen if the app is terminated

Does the Native Android support syncing of data when app is terminated.

Thanks for clarification given.

**Comment by ReallySmallSoftware** [comment]
No, my understanding is that the sync only happens when the app is listening. It may be possible to have something running in the background that is always listening - ie just has an active listener registered, but I believe this is something you would need to code.

**Comment by pavankumarkatakam** [comment]
ok thanks
